# Generated by Django 5.1.3 on 2024-11-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('type_product', models.CharField(blank=True, choices=[('повеска', 'подвеска'), ('кольцо', 'кольцо'), ('брошь', 'брошь'), ('серьги', 'серьги'), ('комплект', 'комплект'), ('пусеты', 'пусеты'), ('другое', 'другое'), ('колье', 'колье'), ('браслет', 'браслет')], default='кольцо', max_length=30)),
                ('price', models.IntegerField()),
                ('create_date', models.DateField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('comment', models.TextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customer.customer')),
            ],
        ),
    ]
