# Generated by Django 5.1.3 on 2024-11-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('согласование', 'согласование'), ('в работе', 'в работе'), ('правки', 'правки'), ('выполнен', 'выполнен'), ('одобрение', 'одобрение')], max_length=20, null=True),
        ),
    ]
