# Generated by Django 5.1.3 on 2024-11-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('согласование', 'согласование'), ('в работе', 'в работе'), ('правки', 'правки'), ('выполнен', 'выполнен'), ('одобрение', 'одобрение'), ('на росте', 'на росте')], max_length=20, null=True),
        ),
    ]
