# Generated by Django 5.1.3 on 2024-11-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_create_date_alter_product_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='work_time',
            field=models.TimeField(default=0.0, null=True),
        ),
    ]
