# Generated by Django 5.1.3 on 2024-11-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_product_work_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='work_time',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
